# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Fri Nov  4 21:22:02 2022
#

import wx
from . import authlib

class no_token(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("No account configured")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, "You have not authorised your Reddit account yet. In order to browse and interact with Reddit, YAARC needs to have access to your account. Click OK to authorise.")
        sizer_1.Add(label_1, 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.authorise = wx.Button(self, wx.ID_ANY, "Authorise")
        sizer_2.Add(self.authorise, 0, 0, 0)

        self.Quit = wx.Button(self, wx.ID_EXIT, "")
        sizer_2.Add(self.Quit, 0, 0, 0)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

        self.authorise.Bind(wx.EVT_BUTTON, self.Authorise)
        self.Quit.Bind(wx.EVT_BUTTON, self.quit)

    def Authorise(self, event):
        authlib.authorise()

    def quit(self, event):
        exit(0)
