# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sat Nov  5 17:32:31 2022
#

import wx
from .authlib import reddit

class main_window(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("YAARC")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.frontpage = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.frontpage, "front-page")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.Posts = wx.ListBox(self.frontpage, wx.ID_ANY, choices=[])
        sizer_2.Add(self.Posts, 0, 0, 0)

        self.Body = wx.TextCtrl(self.frontpage, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        sizer_2.Add(self.Body, 0, 0, 0)

        self.frontpage.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        sizer_1.Fit(self)
        self.Layout()

        self.get_frontpage_posts()
        # Bad idea to do this binding, Because it'll keep reloading whenever the list was cycled through.
        #self.Posts.Bind(wx.EVT_LISTBOX, self.get_frontpage_posts)

# We're only getting submitions from R/Test temporarily.
    def get_frontpage_posts(self):
        posts = list(map(lambda x: x.title, reddit.subreddit("test").random_rising()))
        self.Posts.InsertItems(posts, 0)

    get_frontpage_posts

    # Only here for debugging purposes to make sure the authentication actually worked.
for submission in reddit.subreddit("test").random_rising():
    print(submission.title)